import {Provider} from "./provider";
import "../styles/globals.css";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ({
  children,
}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <Provider>
        <body className="">{children}</body>
      </Provider>
    </html>
  );
}
